spring:
  #进行mysql数据库相关的配置（连接我的虚拟机中的数据库）
  datasource:
    username: root
    password: 1484840359
    url: jdbc:mysql://192.168.48.128:3306/airorderms?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    druid:
      # 需要自定义配置将这些属性进行与druid的属性绑定
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  #配置缓存使用redis
  cache:
    type: redis
  #  进行reis的配置
  redis:
    host: 192.168.48.128
    password: 1484840359
#将springboot应用启动的端口修改为8081
server:
  port: 8081
#指定日志打印级别
logging:
  level:
    com.zrwang.airorderms.mapper: debug
#开启驼峰命名法，可以将数据库中驼峰式命名的字段映射给实体类中
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true